---
- name: New Machine Setup
  hosts: localhost
  become: true
  tasks:
    - ansible.builtin.include_tasks: tasks/zsh.yaml
    - ansible.builtin.include_tasks: tasks/neovim.yaml
    - ansible.builtin.include_tasks: tasks/dotfiles.yaml
