- name: Create Directory for Dotfiles
  ansible.builtin.file:
    path: ~/dotfiles
    state: directory
    mode: u+rwx
- name: Clone Dotfiles
  ansible.builtin.git:
    repo: https://github.com/LuqmanAzhar/dotfiles.git
    dest: ~/dotfiles
    clone: true
    update: true
- name: Set install to Exectuable
  ansible.builtin.file:
    path: ~/dotfiles/install
    state: file
    mode: u+rwx
- name: Running Install Script
  ansible.builtin.shell:
    chdir: ~/dotfiles
    cmd: ./install
