- name: Install zsh
  ansible.builtin.package:
    name: zsh
    state: present
- name: Set zsh for user
  shell: sudo chsh -s $(which zsh)
- name: Install Oh My Zsh
  shell: curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
  become: true
- name: Install Zsh Auto Completions
  ansible.builtin.git:
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/dotfiles
    clone: true
    update: true
